version: "3"

services:
    
    web:
      build: ./web
      ports:
        - "8080:80"
      volumes:
        - ./web/src:/var/www/html
      depends_on:
        - db
      networks:
        - mynet
      restart: always    

    db:
      build: ./db
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      expose:
       - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: root-pw
        MYSQL_DATABASE: mydb
        MYSQL_USER: myname 
        MYSQL_PASSWORD: mypw
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      networks:
       - mynet
      volumes:
       - dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  mynet:
